<a href="https://colab.research.google.com/github/Juank114Gonzalez/Chancuco-SID/blob/master/ChancucoSID.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What is a block?

PL/SQL is a block-structured language. A PL/SQL block is defined by the keywords DECLARE, BEGIN, EXCEPTION, and END, which break up the block into three sections:

**Declarative**: Statements that declare variables, constants, and other code elements, which can then be used within that block  
**Executable**: Statements that are run when the block is executed  
**Exception handling**: A specially structured section you can use to “catch,” or trap, any exceptions that are raised when the executable section runs
Only the executable section is required. You don’t have to declare anything in a block, and you don’t have to trap exceptions raised in that block.

A block itself is an executable statement, so you can nest blocks within other blocks.

```
-- Hello world

BEGIN
  DBMS_OUTPUT.put_line ('Hello World!');
END;

```
The following example block demonstrates the PL/SQL ability to nest blocks within blocks as well as the use of the concatenation operator (||) to join together multiple strings:

```
-- Nested blocks and concatenation
DECLARE
  l_message  
  VARCHAR2 (100) := 'Hello';
BEGIN
  DECLARE
    l_message2     VARCHAR2 (100) := 
      l_message || ' World!'; 
  BEGIN
    DBMS_OUTPUT.put_line (l_message2); -- Print an output
  END;
EXCEPTION
  WHEN OTHERS
  THEN
    DBMS_OUTPUT.put_line 
   (DBMS_UTILITY.format_error_stack);
END;
```

#Blocks naming:

PL/SQL supports the definition of named blocks of code, also known as subprograms. Subprograms can be procedures or functions.


```
-- Named block or subprogram (procedure name is "hello_world")
CREATE OR REPLACE PROCEDURE 
hello_world
IS
  l_message
  VARCHAR2 (100) := 'Hello World!';
BEGIN
  DBMS_OUTPUT.put_line (l_message);
END hello_world;
```

#Variables and constants declaration


Ejemplo simple:

```
DECLARE
    -- Declaración de variables
    v_nombre VARCHAR2(50);
BEGIN
    -- Ejecución de código
    v_nombre := 'Juan';
    DBMS_OUTPUT.PUT_LINE('Hola ' || v_nombre || '!');
EXCEPTION
    -- Manejo de excepciones
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLCODE || ' - ' || SQLERRM);
END;

```
Las variables y constantes se declaran en la sección de declaración del bloque PL/SQL. Se pueden declarar distintos tipos de datos, como VARCHAR2, NUMBER, DATE, BOOLEAN, entre otros. A continuación, se muestran ejemplos de cómo declarar variables y constantes:



```
DECLARE
    -- Declaración de variables
    v_nombre VARCHAR2(50);
    v_edad NUMBER(3);
    v_fecha_nacimiento DATE;
    v_es_casado BOOLEAN := FALSE;
    
    -- Declaración de constantes
    c_pi CONSTANT NUMBER := 3.1416;
    c_saludo CONSTANT VARCHAR2(20) := 'Hola';
BEGIN
    -- Código del bloque
END;
```

#Control Instructions

Las instrucciones de control de flujo en PL/SQL permiten tomar decisiones y controlar la ejecución del código. A continuación, se muestran algunos ejemplos de instrucciones de control:

```
IF v_edad >= 18 THEN
    DBMS_OUTPUT.PUT_LINE('Eres mayor de edad');
ELSE
    DBMS_OUTPUT.PUT_LINE('Eres menor de edad');
END IF;

CASE v_dia_semana
    WHEN 1 THEN DBMS_OUTPUT.PUT_LINE('Lunes');
    WHEN 2 THEN DBMS_OUTPUT.PUT_LINE('Martes');
    WHEN 3 THEN DBMS_OUTPUT.PUT_LINE('Miércoles');
    WHEN 4 THEN DBMS_OUTPUT.PUT_LINE('Jueves');
    WHEN 5 THEN DBMS_OUTPUT.PUT_LINE('Viernes');
    ELSE DBMS_OUTPUT.PUT_LINE('Fin de semana');
END CASE;

FOR i IN 1..10 LOOP
    DBMS_OUTPUT.PUT_LINE('Iteración ' || i);
END LOOP;

WHILE v_edad < 18 LOOP
    v_edad := v_edad + 1;
END LOOP;

EXIT WHEN v_edad >= 18;

```

#Procedures and functions:

Los procedimientos y funciones en PL/SQL se usan para encapsular código y reutilizarlo en diferentes partes de una aplicación. A continuación, se muestran ejemplos de cómo declarar y usar un procedimiento y una función:

```
 Declaración de un procedimiento
PROCEDURE saluda(nombre IN VARCHAR2) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Hola ' || nombre || '!');
END;

-- Declaración de una función
FUNCTION suma(a IN NUMBER, b IN NUMBER) RETURN NUMBER IS
BEGIN
    RETURN a + b;
END;

-- Uso del procedimiento
saluda('Juan');

-- Uso de la función
v_resultado := suma(2, 3);
```


#Exceptions

Una excepción es un evento inesperado que ocurre durante la ejecución de un programa y que interrumpe el flujo normal de ejecución. En PL/SQL, hay dos tipos de excepciones: las excepciones predefinidas y las excepciones definidas por el usuario.  

Las excepciones predefinidas son errores que son definidos por Oracle y que se pueden capturar en el código PL/SQL. Algunas de las excepciones predefinidas incluyen NO_DATA_FOUND, TOO_MANY_ROWS y OTHERS.  

Las excepciones definidas por el usuario son errores que son definidos por el programador y que se pueden capturar en el código PL/SQL. Para capturar una excepción, se utiliza la cláusula EXCEPTION en un bloque PL/SQL. A continuación, se muestra un ejemplo:  

```
BEGIN
  SELECT last_name INTO v_nombre FROM employees WHERE employee_id = 100;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No se encontró ningún empleado con el ID especificado.');
END;

```

En este ejemplo, si no se encuentra ningún empleado con el ID especificado, se captura la excepción NO_DATA_FOUND y se muestra un mensaje en la salida.  

${}$  

|Cláusula	    |Descripción|
|-------------|-----------|
|WHEN OTHERS	|Captura cualquier excepción no especificada y maneja su resultado. Esta cláusula es útil para manejar errores inesperados. Sin embargo, es importante tener en cuenta que capturar todos los errores con WHEN OTHERS puede ocultar errores que deberían ser manejados de forma específica.|
|WHEN ... THEN	|Captura una excepción específica y maneja su resultado. Esta cláusula es útil para manejar errores específicos. Puedes utilizar diferentes cláusulas WHEN para manejar diferentes tipos de excepciones.|
|WHEN NO_DATA_FOUND	|Captura la excepción que se produce cuando una consulta no devuelve ningún resultado y maneja el resultado.|
|WHEN TOO_MANY_ROWS|	Captura la excepción que se produce cuando una consulta devuelve más de una fila y maneja el resultado.|
|WHEN VALUE_ERROR|	Captura la excepción que se produce cuando una asignación o conversión de datos no se puede realizar debido a un tipo de datos incorrecto y maneja el resultado.|
|RAISE	|Lanza una excepción personalizada. Esta cláusula es útil cuando necesitas lanzar una excepción específica en una situación determinada.|
|RAISE_APPLICATION_ERROR	|Lanza una excepción personalizada con un número de error y un mensaje personalizado. Esta cláusula es útil para lanzar una excepción personalizada con un código de error específico y un mensaje personalizado.|
|SQLCODE|	Devuelve el código de error generado por la última operación SQL. Esta cláusula es útil para obtener el código de error de una excepción de SQL y manejarlo de forma específica.|
|SQLERRM|	Devuelve el mensaje de error generado por la última operación SQL. Esta cláusula es útil para obtener el mensaje de error de una excepción de SQL y manejarlo de forma específica.|  

${}$  

```
DECLARE
   n VARCHAR2(10) := '&n'; -- Pedimos al usuario que ingrese un valor para n
   suma NUMBER := 0;
BEGIN
   IF NOT n IS NULL AND n LIKE '%[^0-9]%' THEN -- Validamos que n no sea nulo y que contenga solo números
      RAISE VALUE_ERROR; -- Si n no es un número, lanzamos una excepción VALUE_ERROR
   END IF;
   
   n := TO_NUMBER(n); -- Convertimos el valor de n a un número
   
   IF n < 0 THEN -- Validamos que n no sea negativo
      RAISE APPLICATION_ERROR(-20001, 'El valor de n debe ser mayor o igual a 0.'); -- Si n es negativo, lanzamos una excepción personalizada
   END IF;
   
   FOR i IN 1..n LOOP
      suma := suma + i;
   END LOOP;
   
   DBMS_OUTPUT.PUT_LINE('La suma de los ' || n || ' primeros números naturales es: ' || suma);
EXCEPTION
   WHEN VALUE_ERROR THEN -- Manejamos la excepción VALUE_ERROR
      DBMS_OUTPUT.PUT_LINE('El valor de n debe ser un número.'); -- Mostramos un mensaje indicando el error al usuario
   WHEN OTHERS THEN -- Manejamos todas las otras excepciones
      DBMS_OUTPUT.PUT_LINE('Error: ' || SQLCODE || ' - ' || SQLERRM); -- Mostramos un mensaje de error genérico que incluye el código y la descripción del error
END;
```  

${}$  

Este bloque PL/SQL es un ejemplo de cómo se pueden utilizar las cláusulas de excepción para manejar errores en tiempo de ejecución y mostrar mensajes personalizados al usuario.

#SQL cursors


Un cursor es un objeto que permite recorrer los registros devueltos por una consulta SQL de forma individual. Los cursores se utilizan principalmente en programas PL/SQL que necesitan procesar los registros devueltos por una consulta SQL uno por uno.  


Para declarar un cursor en PL/SQL, se utiliza la siguiente sintaxis:

```
CURSOR nombre_cursor IS SELECT columna1, columna2, ... FROM tabla WHERE condicion;

```

#Triggers  

Los triggers son objetos de base de datos que se utilizan para ejecutar un conjunto de instrucciones automáticamente en respuesta a un evento específico en una tabla, vista, o esquema de base de datos. Se pueden utilizar para auditar cambios en los datos, validar entradas, sincronizar datos en varias tablas, entre otros usos. La sintaxis para crear un trigger es la siguiente:

```
CREATE [OR REPLACE] TRIGGER nombre_trigger
{BEFORE | AFTER | INSTEAD OF} {INSERT | UPDATE | DELETE | DROP | ALTER}
ON nombre_tabla
[REFERENCING {OLD AS old | NEW AS new}]
[FOR EACH ROW]
[WHEN condicion]
DECLARE
  -- Declaraciones de variables
BEGIN
  -- Conjunto de instrucciones a ejecutar
EXCEPTION
  -- Manejo de excepciones
END;
```  

#BEFORE, AFTER e INSTEAD OF
Los triggers BEFORE, AFTER e INSTEAD OF especifican cuándo se ejecuta el conjunto de instrucciones definido en el cuerpo del trigger. Los triggers BEFORE se ejecutan antes de que se realice la operación en la tabla, los AFTER se ejecutan después de que se realiza la operación en la tabla, y los INSTEAD OF se ejecutan en lugar de la operación en la tabla. Aquí hay algunos ejemplos que ilustran la diferencia entre estos tipos de triggers:  
```
-- Trigger BEFORE para actualizar la fecha de modificación de una fila
CREATE OR REPLACE TRIGGER tr_fecha_modificacion
BEFORE UPDATE ON tabla_ejemplo
FOR EACH ROW
BEGIN
  :NEW.fecha_modificacion := SYSDATE;
END;

-- Trigger AFTER para auditar cambios en una tabla
CREATE OR REPLACE TRIGGER tr_auditoria
AFTER INSERT OR UPDATE OR DELETE ON tabla_auditoria
FOR EACH ROW
DECLARE
  -- Declaraciones de variables
BEGIN
  -- Conjunto de instrucciones para auditar cambios
EXCEPTION
  -- Manejo de excepciones
END;

-- Trigger INSTEAD OF para sincronizar datos en dos tablas
CREATE OR REPLACE TRIGGER tr_sincronizacion
INSTEAD OF INSERT OR UPDATE OR DELETE ON tabla_1
FOR EACH ROW
DECLARE
  -- Declaraciones de variables
BEGIN
  -- Conjunto de instrucciones para sincronizar datos en tabla_2
EXCEPTION
  -- Manejo de excepciones
END;
```